version: "2.0"
name: mflowtrackingserver

services:
  ui:
    container_name: mlflow-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - ${MLFLOW_PORT}:5000
    # backend-store-uri --> mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@{db-service name}:3306/${MYSQL_DATABASE} 
    # default-artifact-root ${ARTIFACT_ROOT}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000
  #RDBMS for managing mlflow database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  #Adminer was giving connection issues so we shifted to phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPADMIN_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  # For finding ip on docker
  # ip addr
  # For checking which services are running
  # docker ps
  # For creating image build and running application
  # docker-compose --env-file .env  up
