version: "2.0"
name: mflowtrackingserver

services:
  ui:
    build:
      context: .\ui\.
    # container_name: mlflow-ui
    # image: shivgupta121/mflowtrackingserver-ui:mlflow_ctr
    ports:
      - ${MLFLOW_PORT}:5000
    # backend-store-uri --> mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@{db-service name}:3306/${MYSQL_DATABASE} 
    # default-artifact-root ${ARTIFACT_ROOT}
    restart: always
    volumes:
      - artifactStore:/mlruns

    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE} --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000
    # command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE} --file-store ./mlruns --host 0.0.0.0 --port 5000

    #RDBMS for managing mlflow database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #Adminer was giving connection issues so we shifted to phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPADMIN_PORT}:80
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  artifactStore:
    external: true
  # For finding ip on docker
  # ip addrs
  # For checking which services are running
  # docker ps
  # For creating image build and running application
  # docker-compose --env-file .env  up
  # For generating deployment yamls
  # kompose convert -f ./docker-compose.yml -o ./deploy/
