apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    io.kompose.service: ui
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - args:
            - mlflow
            - server
            - --backend-store-uri
            - mysql+pymysql://mlflow_user:mlflow_pass@db:3306/mlflow
            - --default-artifact-root
            - ./mlruns
            - --host
            - 0.0.0.0
            - --port
            - "5000"
          image: ' '
          name: mlflow-ui
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mlflow-ui
        from:
          kind: ImageStreamTag
          name: ui:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
